config/routes.rb
Boozr::Application.routes.draw do
  resources :stores, :only => [:index,:show]

  resources :products, :only => [:index, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'open-uri'

class ProductsController < ApplicationController
  def index
  	page = params[:yip] || "/products?page=1"

    if params[:search]
      products_json = open("http://lcboapi.com/#{page}&q=#{params[:search]}").read
    else
      products_json = open("http://lcboapi.com/#{page}").read
    end

    @products = JSON.parse(products_json)



  end

  def show
  	id = params[:id]
  	product_json = open("http://lcboapi.com/products/#{id}").read
  	@product = JSON.parse(product_json)

    product_inventory_json = open("http://lcboapi.com/products/#{id}/stores").read
    @product_inventory = JSON.parse(product_inventory_json)

  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
  	page = params[:dip] || 1
  	stores_json = open("http://lcboapi.com/stores?page=#{page}").read
    @stores = JSON.parse(stores_json)
  end

  def show
  	id = params[:id]
  	store_json = open("http://lcboapi.com/stores/#{id}").read
  	@store = JSON.parse(store_json)

	 	elev_json = open("http://maps.googleapis.com/maps/api/elevation/json?sensor=false&locations=#{@store['result']['latitude']},#{@store['result']['longitude']}").read
		@store_elev = JSON.parse(elev_json)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boozr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "stores", stores_path %>
<%= link_to "products", products_path %>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Liquor Control Board of Ontario</h1>
<h2>"It's for your own good."</h2>

<p>
	<%= form_tag products_path, :method => 'get' do %>
	<%= text_field_tag :search %>
	<%= submit_tag :search %>
	<% end %>
</p>

<section>
<table>
	<thead>
		<tr>
			<td><h3>Product</h3></td>
			<td><h3>Type</h3></td>
		</tr>
	</thead>
	<tbody>

<% if @products['pager']['total_record_count'] == 0  %>
	No results found for search term "<%= params[:search]  %>"
<% else %>
	<% @products['result'].each do |p| %>
		<tr>
	    <td><%= link_to p['name'], product_path(p['id']) %></td>
	    <td><%= p['primary_category'] %></td>
	  </tr>
		<% end %>
<% end %>

	</tbody>
</table>
</section>

<% if @products['pager']['next_page_path'] %>
	<p><%= link_to "next >>", products_path(:yip => @products['pager']['next_page_path']) %></p>
	<p><%= link_to "<< prev", products_path(:yip => @products['pager']['previous_page_path']) %></p>
<% end %>

<p><%= @products['pager']['current_page']%></p>

app/views/products/show.html.erb
<h1><%= @product['result']['name'] %></h1>
<p><%= image_tag(@product['result']['image_thumb_url']) %></p>

<h1>Stock for this product</h1>
<table>
	<thead>
		<tr>
			<td><h2>Store</h2></td>
			<td><h2>City</h2></td>
			<td><h2>Quantity</h2></td>

		</tr>
	</thead>
	<tbody>
	<% @product_inventory['result'].each do |r| %>



<tr>
	<td><%= r['name'] %></td>
	<td><%= r['city'] %></td>
	<td><%= r['quantity'] %></td>

</tr>
<% end %>
</tbody>
</table>
<p><%= link_to "back", products_path %></p>

app/views/stores/index.html.erb
<h1>Stores#index</h1>

<section>
<table>
	<thead>
		<tr>
			<td><h3>Store</h3></td>
			<td><h3>City</h3></td>
		</tr>
	</thead>
	<tbody>

<% @stores['result'].each do |s| %>
	<tr>

    <td><%= link_to s['name'], store_path(s['id']) %></td>
    <td><%= s['city'] %>
  </tr>
	<% end %>
	</tbody>
</table>
</section>



<p><%= link_to "next >>", stores_path(:dip => @stores['pager']['next_page']) %></p>
<p><%= link_to "<< prev", stores_path(:dip => @stores['pager']['previous_page']) %></p>
<p><%= @stores['pager']['current_page']%></p>

app/views/stores/show.html.erb
<h1>Store</h1>

<ul>

<li><%= @store['result']['name']%>
<li><%= @store['result']['city']%>
<li>Elevation <%= @store_elev['results'][0]['elevation'].ceil %> metres (Google)</li>

</ul>

<%= link_to "back", stores_path %>